// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LogApi.Entities;

public partial class Applications
{
    public int Id { get; set; }

    public string AppName { get; set; }

    public string AppDescription { get; set; }

    public DateTime DateCreated { get; set; }

    public bool Active { get; set; }

    public virtual ICollection<AppLogs> AppLogs { get; set; } = new List<AppLogs>();
}