// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace LogApi.Entities;

public partial class AppLogsContext : DbContext
{
    public AppLogsContext(DbContextOptions<AppLogsContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AppLogs> AppLogs { get; set; }

    public virtual DbSet<Applications> Applications { get; set; }

    public virtual DbSet<GetLogsView> GetLogsView { get; set; }

    public virtual DbSet<GetMinMaxDatesView> GetMinMaxDatesView { get; set; }

    public virtual DbSet<LogTypes> LogTypes { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AppLogs>(entity =>
        {
            entity.Property(e => e.AppUser)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.AppVersion).HasMaxLength(50);
            entity.Property(e => e.LogMessage).IsRequired();

            entity.HasOne(d => d.App).WithMany(p => p.AppLogs)
                .HasForeignKey(d => d.AppId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AppLogs_Applications1");

            entity.HasOne(d => d.LogType).WithMany(p => p.AppLogs)
                .HasForeignKey(d => d.LogTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AppLogs_LogTypes");
        });

        modelBuilder.Entity<Applications>(entity =>
        {
            entity.Property(e => e.Active).HasDefaultValue(true, "DF_Applications_Active");
            entity.Property(e => e.AppDescription)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.AppName)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.DateCreated).HasDefaultValueSql("(getdate())", "DF_Applications_DateCreated");
        });

        modelBuilder.Entity<GetLogsView>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("GetLogsView");

            entity.Property(e => e.AppName)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.AppUser)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.AppVersion).HasMaxLength(50);
            entity.Property(e => e.LogMessage).IsRequired();
            entity.Property(e => e.LogType)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<GetMinMaxDatesView>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("GetMinMaxDatesView");
        });

        modelBuilder.Entity<LogTypes>(entity =>
        {
            entity.Property(e => e.LogType)
                .IsRequired()
                .HasMaxLength(50);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}