// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LogApi.Entities;

public partial class GetLogsView
{
    public int Id { get; set; }

    public int AppId { get; set; }

    public string AppVersion { get; set; }

    public string AppUser { get; set; }

    public DateTime LogDate { get; set; }

    public string LogMessage { get; set; }

    public int LogTypeId { get; set; }

    public string SendEmailAddressList { get; set; }

    public string AppName { get; set; }

    public string LogType { get; set; }
}