// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LogApi.Entities;

public partial class GetMinMaxDatesView
{
    public DateTime? MaxDate { get; set; }

    public DateTime? MinDate { get; set; }
}