// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LogApi.Entities;

public partial class LogTypes
{
    public int Id { get; set; }

    public string LogType { get; set; }

    public virtual ICollection<AppLogs> AppLogs { get; set; } = new List<AppLogs>();
}